GET http://localhost:5000/api/notes

#GET http://localhost:5000/api/users

# PUT http://localhost:5000/api/userroles/deleterole/1000
# Content-Type: application/json

# {
#     "RoleId": 1000
# }


POST http://localhost:5000/api/users
Content-Type: application/json

 {
     "FirstName":"fgf",
     "LastName": "Fgjj",
     "Email": "blabla",
     "Login": "ktkachenko",
     "Password": "blabla",
     "Image": "hgyh"
 }


DELETE http://localhost:5000/api/users/8
Content-Type: application/json
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjpbIlN1cGVyQWRtaW4iLCJBZG1pbiJdLCJ1bmlxdWVfbmFtZSI6Ik5hdGFsaSIsIm5iZiI6MTU4NjQyNzY5OCwiZXhwIjoxNTg2NDI5NDk4LCJpYXQiOjE1ODY0Mjc2OTh9.FmqcyzYge_5Pf_I-h0RCtX7MNKJVfrYhBg-ub6G7tQo
